[server]
enableStaticServing = true

[theme]
primaryColor="#233B91"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#30D0C8"
textColor="#1A2D52"
headingFont="Bebas Neue"

[[theme.fontFaces]]
url = "app/static/BebasNeue-Regular.ttf"
family = "Bebas Neue"